mod binary_search;
mod binary_watch;
mod combinations;
mod combo_phone;
mod count_build_good_strings;
mod counting_bits;
mod destructest;
mod divide_players;
mod first_bad_version;
mod flood_fill;
mod four_sum;
mod grind_75;
mod happy_number;
mod inorder_binary_tree_traversal;
mod isomorphic_strings;
mod longest_non_repeating_substring;
mod matrix_01;
mod max_depth_bin_tree;
mod max_num_of_operations;
mod merge_strings_alternately;
mod merge_two_bin_trees;
mod merge_two_sorted_lists;
mod middle_linked_list;
mod solution;
// mod min_depth_tree;
mod pascal;
mod path_sum;
mod permutation_in_a_string;
mod permutations;
mod remove_nth_from_end;
mod remove_nth_from_end_2;
mod reverse_words_string;
mod shortest_distance_to_character;
mod twosum;
mod zigzag_conversion;
fn main() {
    // pascal();
}
